### PR TITLE
Enabling translation of error page title

### LINKED ISSUE #23: "Page not Found" title in different languages
Hello!

Today I found that in every language my title looks the same:

```
Page not Found — sitename
```

Maybe need to put +1 line to `languages.yaml`:

``` yaml
PLUGIN_ERROR:
    ERROR: "Error"
    ERROR_MESSAGE: "Woops. Looks like this page doesn't exist."
    ERROR_TITLE_404: "Page not found"
```

and correctly handle this?

### PR DESCRIPTION
**Pull request by rbukovansky**
This should resolve #23

### CODE REVIEW

**Comment by rbukovansky** [comment]
@flaviocopes Could you please merge this one as well if it's OK? Thanks.

**Comment by rbukovansky** [comment]
@flaviocopes OK. Any idea how to do it?

BTW I have updated README as well, stating that change in settings is needed to work properly.

**Comment by rbukovansky** [comment]
@flaviocopes Have you thought about how to workaround that, please? Thanks.

**Comment by flaviocopes** [comment]
No I didn't come up with a solution that's generally applicable without breaking backwards compatibility with the current release

**Comment by rbukovansky** [comment]
@rhukster Why was this merged and then reverted few seconds later?

**Comment by rhukster** [comment]
Because it broke 'out of the box' due to the requirement to enable Twig processing in frontmatter.  This is not an acceptable tradeoff.  I think this can be done by setting the title programmatically from the plugin rather than via twig in page frontmatter.

I was in the middle of Grav 1.4 release and didn't have time to fiddle with it.

**Pull request merged**
